#!/usr/bin/env python
# -*- coding: utf-8 -*-

global_attr_dict = {
    'title' : 'TODO',
    'summary' : 'TODO',
    'type' : 'TODO',
    'id' : 'TODO',
    'project' : 'TODO',
    'references' : 'TODO',
    'institution' : 'Imperial College London',
    'contact' : 'simon.moulds@imperial.ac.uk',
    'comment' : 'TODO',
    'conventions' : 'CF-1.6',
    'standard_name_vocabulary' : 'NetCDF Climate and Forecast (CF) Standard Names version 21',
    'keywords' : 'land cover classification',
    'keywords_vocabulary' : 'NASA Global Change Master Directory (GCMD) Science Keywords',
    'license' : 'TODO',
    'naming_authority' : 'TODO',
    'TileSize' : 'TODO',
    'tracking_id' : 'TODO',
    'product_version' : 'TODO',
    'date_created' : 'TODO',
    'creator_name' : 'Simon Moulds',
    'creator_url' : 'https://www.imperial.ac.uk/people/simon.moulds',
    'creator_email' : 'simon.moulds@imperial.ac.uk',
    'source' : 'ESACCI-LC-L4-LCCS-Map-300m-P1Y',
    'history' : 'TODO',
    'time_coverage_start' : 'TODO',
    'time_coverage_end' : 'TODO',
    'time_coverage_duration' : 'TODO',
    'time_coverage_resolution' : 'TODO',
    'geospatial_lat_min' : 'TODO',
    'geospatial_lat_max' : 'TODO',
    'geospatial_lon_min' : 'TODO',
    'geospatial_lon_max' : 'TODO',
    'spatial_resolution' : 'TODO',
    'geospatial_lat_units' : 'TODO',
    'geospatial_lat_resolution' : 'TODO',
    'geospatial_lon_units' : 'TODO',
    'geospatial_lon_resolution' : 'TODO',
    'pft_table' : 'TODO',
    'grid_name' : 'TODO',
    'pft_table_comment' : 'TODO',
    'spatialResolutionNominal' : 'TODO'
}
