title = "JAMR example configuration"

[main]
grass_gis_database = '/exports/geos.ed.ac.uk/moulds_hydro/grassdata'
data_directory = '/exports/geos.ed.ac.uk/moulds_hydro/data'
scratch_directory = '/exports/geos.ed.ac.uk/moulds_hydro/scratch'

[landfraction]

[topography]
[topography.merit]
data_directory = '/exports/geos.ed.ac.uk/moulds_hydro/data/MERIT/dem'

[landcover]

[soil]
