title = "JAMR example configuration"

[main]
gisdb = '/exports/geos.ed.ac.uk/moulds_hydro/grassdata'
scratch = '/exports/geos.ed.ac.uk/moulds_hydro/scratch'

[landfraction]

[topography]
[topography.merit]
data_directory = '/exports/geos.ed.ac.uk/moulds_hydro/data/MERIT/dem'

[landcover]

[soil]
